AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'zzz/**/*'

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
  VersionAdded: '0.9'
  AllowedConstants: []
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
